server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway

zuul: 
  # ignored-services: microservicecloud-dept                                   # 隐藏真实的服务名称 
  ignored-services: "*"                                                        # 隐藏所有服务的真实名称
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**

eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
    
info:
  app.name: hochenchong-microservicecloud
  company.name: hochenchong
  build.artifactId: $project.artifactId$
  build.version: $project.version$